# Generated by Django 6.0.1 on 2026-01-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_sitecustomization"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enable_music",
                    models.BooleanField(default=True, verbose_name="Habilitar Músicas"),
                ),
                (
                    "enable_quiz",
                    models.BooleanField(default=True, verbose_name="Habilitar Quiz"),
                ),
                (
                    "enable_polaroids",
                    models.BooleanField(default=True, verbose_name="Habilitar Fotos"),
                ),
                (
                    "enable_amo_list",
                    models.BooleanField(
                        default=True, verbose_name="Habilitar Lista Amo"
                    ),
                ),
                (
                    "enable_custom_messages",
                    models.BooleanField(
                        default=True, verbose_name="Habilitar Cartinha"
                    ),
                ),
                (
                    "max_polaroids",
                    models.IntegerField(default=8, verbose_name="Máximo de Fotos"),
                ),
                (
                    "max_music_songs",
                    models.IntegerField(default=3, verbose_name="Máximo de Músicas"),
                ),
                (
                    "max_amo_messages",
                    models.IntegerField(
                        default=50, verbose_name="Máximo de Mensagens Amo"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Modo Manutenção"),
                ),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem de Manutenção"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
                "db_table": "system_config",
            },
        ),
    ]
