# Generated by Django 4.2.27 on 2026-02-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_systemconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AlterField(
            model_name="sitecustomization",
            name="name",
            field=models.CharField(
                default="Insira o nome aqui", max_length=255, verbose_name="Nome"
            ),
        ),
    ]
