# Generated by Django 4.2.27 on 2026-02-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_accountverificationtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailVerificationToken",
        ),
    ]
