# Generated by Django 4.2.27 on 2026-02-11 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_emailchangetoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomizationDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Insira o nome aqui",
                        max_length=255,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Início"
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("dark", "Escuro"), ("light", "Claro")],
                        default="dark",
                        max_length=20,
                        verbose_name="Tema",
                    ),
                ),
                ("amo_list", models.JSONField(default=list, verbose_name="Lista Amo")),
                (
                    "amo_favorites",
                    models.JSONField(default=list, verbose_name="Favoritos Amo"),
                ),
                ("polaroids", models.JSONField(default=list, verbose_name="Polaroids")),
                (
                    "quiz_score",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Pontuação do Quiz"
                    ),
                ),
                (
                    "last_song",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Última Música",
                    ),
                ),
                (
                    "liked_song",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Música Curtida",
                    ),
                ),
                (
                    "favorite_message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mensagem Favorita"
                    ),
                ),
                (
                    "custom_messages",
                    models.JSONField(
                        default=list, verbose_name="Mensagens Personalizadas"
                    ),
                ),
                (
                    "custom_data",
                    models.JSONField(default=dict, verbose_name="Dados Personalizados"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customization_draft",
                        to="api.order",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rascunho de Personalização",
                "verbose_name_plural": "Rascunhos de Personalização",
                "db_table": "customization_drafts",
                "ordering": ["-updated_at"],
            },
        ),
    ]
