# Generated by Django 4.2.27 on 2026-02-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_customizationdraft"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Email para Envio do Pedido",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Token Único",
            ),
        ),
        migrations.DeleteModel(
            name="CustomizationDraft",
        ),
    ]
