# Generated by Django 4.2.27 on 2026-02-11 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_add_order_token_and_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderEmailVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Email para Verificação"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True, max_length=255, unique=True, verbose_name="Token"
                    ),
                ),
                ("used", models.BooleanField(default=False, verbose_name="Usado")),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_email_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token de Verificação de Email de Pedido",
                "verbose_name_plural": "Tokens de Verificação de Email de Pedido",
                "db_table": "order_email_verification_tokens",
                "ordering": ["-created_at"],
            },
        ),
    ]
