# Generated by Django 5.2.12 on 2026-04-22 18:30

from django.db import migrations, models


def backfill_youtube_music_links(apps, schema_editor):
    SiteCustomization = apps.get_model("api", "SiteCustomization")
    for sc in SiteCustomization.objects.iterator():
        links = []
        data = sc.custom_data or {}
        for v in data.get("youtube_videos") or []:
            if isinstance(v, dict):
                u = (v.get("url") or "").strip()
                vid = v.get("id")
                if not u and vid:
                    u = f"https://www.youtube.com/watch?v={vid}"
                if u:
                    links.append(u)
            elif isinstance(v, str) and v.strip():
                links.append(f"https://www.youtube.com/watch?v={v.strip()}")
        sc.youtube_music_links = links
        sc.save(update_fields=["youtube_music_links"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_add_order_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecustomization",
            name="youtube_music_links",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Links das músicas"
            ),
        ),
        migrations.RunPython(backfill_youtube_music_links, migrations.RunPython.noop),
    ]
