# Generated by Django 5.2.12 on 2026-05-11 13:51

from django.db import migrations, models


def backfill_audio_urls(apps, schema_editor):
    SiteCustomization = apps.get_model("api", "SiteCustomization")
    for sc in SiteCustomization.objects.iterator():
        data = sc.custom_data or {}
        all_a = []
        c_only = []
        for v in data.get("youtube_videos") or []:
            if isinstance(v, dict):
                au = (v.get("audio_url") or "").strip()
                if au:
                    all_a.append(au)
                    if "res.cloudinary.com" in au or "/cloudinary.com/" in au:
                        c_only.append(au)
        SiteCustomization.objects.filter(pk=sc.pk).update(
            audio_urls=all_a,
            cloudinary_audio_urls_only=c_only,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_sitecustomization_youtube_music_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitecustomization",
            name="audio_urls",
            field=models.JSONField(
                blank=True, default=list, verbose_name="URLs de áudio"
            ),
        ),
        migrations.AddField(
            model_name="sitecustomization",
            name="cloudinary_audio_urls_only",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="URLs Cloudinary (apenas res.cloudinary.com)",
            ),
        ),
        migrations.RunPython(backfill_audio_urls, noop_reverse),
    ]
