# Generated by Django 5.2.12 on 2026-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_sitecustomization_audio_url_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpsAlertEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Quando"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Categoria"
                    ),
                ),
                ("message", models.TextField(verbose_name="Mensagem")),
                (
                    "detail",
                    models.TextField(blank=True, default="", verbose_name="Detalhe"),
                ),
                (
                    "body_excerpt",
                    models.TextField(
                        blank=True, default="", verbose_name="Corpo (trecho)"
                    ),
                ),
                (
                    "extra",
                    models.JSONField(blank=True, null=True, verbose_name="Extra"),
                ),
            ],
            options={
                "verbose_name": "Evento de alerta (ops)",
                "verbose_name_plural": "Eventos de alerta (ops)",
                "db_table": "ops_alert_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
