# Generated by Django 5.2.12 on 2026-05-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_ops_alert_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteEngagementTotals",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "instagram_clicks",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Cliques Instagram"
                    ),
                ),
                (
                    "tiktok_clicks",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Cliques TikTok"
                    ),
                ),
                (
                    "support_modal_opens",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="Aberturas modal suporte"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Totais de engajamento (site)",
                "verbose_name_plural": "Totais de engajamento (site)",
                "db_table": "site_engagement_totals",
            },
        ),
        migrations.CreateModel(
            name="OrderEngagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_image_hits",
                    models.PositiveIntegerField(
                        default=0, verbose_name="GET imagem QR (e-mail/prévia)"
                    ),
                ),
                (
                    "qr_download_hits",
                    models.PositiveIntegerField(default=0, verbose_name="Download QR"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement",
                        to="api.order",
                        verbose_name="Pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Engajamento do pedido",
                "verbose_name_plural": "Engajamentos dos pedidos",
                "db_table": "order_engagement",
            },
        ),
    ]
