# Generated by Django 5.2.12 on 2026-06-18 18:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_engagement_counters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nome")),
                (
                    "slug",
                    models.SlugField(max_length=120, unique=True, verbose_name="Slug"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Ícone (emoji ou classe)",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "db_table": "categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="sitecustomization",
            name="order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="order",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="order",
            name="token",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="enable_amo_list",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="enable_custom_messages",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="enable_music",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="enable_polaroids",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="enable_quiz",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="max_amo_messages",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="max_music_songs",
        ),
        migrations.RemoveField(
            model_name="systemconfig",
            name="max_polaroids",
        ),
        migrations.AddField(
            model_name="order",
            name="customer_name",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Nome do cliente"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Telefone"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, default="", verbose_name="Observações"),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Endereço"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="UF"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zip",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="free_shipping_min",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("299.00"),
                max_digits=10,
                verbose_name="Frete grátis acima de",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="store_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Endereço"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="store_email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="E-mail de contato"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="store_name",
            field=models.CharField(
                default="AutoPeças Sandroni",
                max_length=120,
                verbose_name="Nome da loja",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="store_phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Telefone"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="store_tagline",
            field=models.CharField(
                default="Peças automotivas com qualidade e confiança",
                max_length=255,
                verbose_name="Slogan",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="store_whatsapp",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="WhatsApp"
            ),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=80,
                        verbose_name="SKU / Código",
                    ),
                ),
                (
                    "oem_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=80,
                        verbose_name="Código OEM",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=120,
                        verbose_name="Marca",
                    ),
                ),
                (
                    "compatible_vehicles",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Ex: Gol 1.0 2012-2016; Palio 1.4 2010-2015",
                        verbose_name="Veículos compatíveis",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço"
                    ),
                ),
                (
                    "compare_at_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço anterior",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(default=0, verbose_name="Estoque"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Imagem principal",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="api.category",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cadastrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Peça",
                "verbose_name_plural": "Peças",
                "db_table": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Nome da peça"),
                ),
                (
                    "product_sku",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="SKU"
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço unitário"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="Imagem"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="api.product",
                        verbose_name="Peça",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item do pedido",
                "verbose_name_plural": "Itens do pedido",
                "db_table": "order_items",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Texto alternativo",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Ordem"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="api.product",
                        verbose_name="Peça",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da peça",
                "verbose_name_plural": "Imagens das peças",
                "db_table": "product_images",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.DeleteModel(
            name="OrderEngagement",
        ),
        migrations.DeleteModel(
            name="SiteCustomization",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-created_at"], name="products_is_acti_b753ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_featured", "-created_at"],
                name="products_is_feat_0a930b_idx",
            ),
        ),
    ]
