# Generated by Django 5.2.12 on 2026-06-18 22:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_welcome_coupon(apps, schema_editor):
    Coupon = apps.get_model('api', 'Coupon')
    if not Coupon.objects.filter(code='BEMVINDO10').exists():
        Coupon.objects.create(
            code='BEMVINDO10',
            discount_type='percent',
            discount_value=Decimal('10.00'),
            first_purchase_only=True,
            min_order_amount=Decimal('50.00'),
            is_active=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_marketplace"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=40, unique=True, verbose_name="Código"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentual"), ("fixed", "Valor fixo")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Valor do desconto",
                    ),
                ),
                (
                    "first_purchase_only",
                    models.BooleanField(
                        default=False, verbose_name="Somente primeira compra"
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Pedido mínimo",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Limite de usos"
                    ),
                ),
                (
                    "used_count",
                    models.PositiveIntegerField(default=0, verbose_name="Vezes usado"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expira em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cupom",
                "verbose_name_plural": "Cupons",
                "db_table": "coupons",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="carrier",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Transportadora"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="Cupom"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Desconto aplicado",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Enviado em"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(
                choices=[
                    ("pending", "Aguardando envio"),
                    ("processing", "Em separação"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregue"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status do envio",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Código de rastreio"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="google_analytics_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=40,
                verbose_name="Google Analytics ID",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="meta_pixel_id",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="Meta Pixel ID"
            ),
        ),
        migrations.AlterField(
            model_name="systemconfig",
            name="store_name",
            field=models.CharField(
                default="Galelugi Peças", max_length=120, verbose_name="Nome da loja"
            ),
        ),
        migrations.CreateModel(
            name="AbandonedCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("items", models.JSONField(default=list, verbose_name="Itens")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "reminder_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Lembrete enviado em"
                    ),
                ),
                (
                    "recovered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Recuperado em"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abandoned_carts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carrinho abandonado",
                "verbose_name_plural": "Carrinhos abandonados",
                "db_table": "abandoned_carts",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RunPython(seed_welcome_coupon, migrations.RunPython.noop),
    ]
