# Generated by Django 5.2.12 on 2026-06-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_growth_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="shipping_address",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Endereço"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_city",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="Cidade"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_state",
            field=models.CharField(
                blank=True, default="", max_length=2, verbose_name="UF"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_zip",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="CEP"
            ),
        ),
    ]
