# Generated by Django 5.2.12 on 2026-06-19 15:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_user_shipping_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=80, unique=True, verbose_name="Marca"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=80, unique=True, verbose_name="Slug"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Marca veículo",
                "verbose_name_plural": "Marcas veículos",
                "db_table": "vehicle_brands",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_days",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Prazo (dias)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_provider",
            field=models.CharField(
                blank=True,
                default="fixed",
                max_length=40,
                verbose_name="Provedor de frete",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_service_name",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Serviço de frete"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_carrier",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Transportadora"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Enviado em"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_shipping_status",
            field=models.CharField(
                choices=[
                    ("pending", "Aguardando envio"),
                    ("processing", "Em separação"),
                    ("shipped", "Enviado"),
                    ("delivered", "Entregue"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status envio (vendedor)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item_tracking_code",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Rastreio"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="seller_balance_credited",
            field=models.BooleanField(default=False, verbose_name="Repasse creditado"),
        ),
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Usado para calcular margem nas peças da plataforma",
                max_digits=10,
                null=True,
                verbose_name="Custo de aquisição",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="height_cm",
            field=models.PositiveIntegerField(default=10, verbose_name="Altura (cm)"),
        ),
        migrations.AddField(
            model_name="product",
            name="length_cm",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Comprimento (cm)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_kg",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("1.000"),
                max_digits=6,
                verbose_name="Peso (kg)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width_cm",
            field=models.PositiveIntegerField(default=20, verbose_name="Largura (cm)"),
        ),
        migrations.AddField(
            model_name="seller",
            name="balance_available",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Saldo disponível",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="balance_pending",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Saldo pendente (saques)",
            ),
        ),
        migrations.AddField(
            model_name="seller",
            name="pix_key",
            field=models.CharField(
                blank=True,
                default="",
                max_length=120,
                verbose_name="Chave PIX para repasse",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="melhor_envio_sandbox",
            field=models.BooleanField(
                default=True, verbose_name="Melhor Envio sandbox"
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="melhor_envio_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Token Melhor Envio",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="minimum_payout_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                max_digits=10,
                verbose_name="Saque mínimo vendedor",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="origin_zip",
            field=models.CharField(
                blank=True,
                default="01310100",
                max_length=12,
                verbose_name="CEP de origem (frete)",
            ),
        ),
        migrations.AddField(
            model_name="systemconfig",
            name="stock_reservation_minutes",
            field=models.PositiveIntegerField(
                default=30, verbose_name="Reserva de estoque (minutos)"
            ),
        ),
        migrations.CreateModel(
            name="ProductConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Última mensagem"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_conversations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Comprador",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="api.product",
                        verbose_name="Peça",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="api.seller",
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversa sobre peça",
                "verbose_name_plural": "Conversas sobre peças",
                "db_table": "product_conversations",
                "ordering": ["-last_message_at"],
                "unique_together": {("product", "buyer")},
            },
        ),
        migrations.CreateModel(
            name="ProductMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(verbose_name="Mensagem")),
                ("is_read", models.BooleanField(default=False, verbose_name="Lida")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviada em"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="api.productconversation",
                        verbose_name="Conversa",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Remetente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensagem",
                "verbose_name_plural": "Mensagens",
                "db_table": "product_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=80, verbose_name="Motivo")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Descrição"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitada"),
                            ("approved", "Aprovada"),
                            ("rejected", "Rejeitada"),
                            ("item_shipped", "Item enviado pelo cliente"),
                            ("received", "Item recebido"),
                            ("refunded", "Reembolsado"),
                            ("closed", "Encerrada"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "seller_response",
                    models.TextField(
                        blank=True, default="", verbose_name="Resposta vendedor"
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Notas admin"
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor reembolso",
                    ),
                ),
                (
                    "return_tracking_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Rastreio devolução",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="api.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="api.orderitem",
                        verbose_name="Item",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to="api.seller",
                        verbose_name="Vendedor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Devolução",
                "verbose_name_plural": "Devoluções",
                "db_table": "return_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor"
                    ),
                ),
                ("pix_key", models.CharField(max_length=120, verbose_name="Chave PIX")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando"),
                            ("processing", "Em processamento"),
                            ("paid", "Pago"),
                            ("rejected", "Rejeitado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, default="", verbose_name="Notas admin"
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Comprovante / ID PIX",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Processado em"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="api.seller",
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Repasse vendedor",
                "verbose_name_plural": "Repasses vendedores",
                "db_table": "seller_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Modelo")),
                ("slug", models.SlugField(max_length=120, verbose_name="Slug")),
                ("year_start", models.PositiveIntegerField(verbose_name="Ano inicial")),
                ("year_end", models.PositiveIntegerField(verbose_name="Ano final")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="api.vehiclebrand",
                        verbose_name="Marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo veículo",
                "verbose_name_plural": "Modelos veículos",
                "db_table": "vehicle_models",
                "ordering": ["brand__name", "name"],
                "unique_together": {("brand", "slug")},
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(verbose_name="Nota (1-5)")),
                (
                    "title",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="Título"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Comentário"),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False, verbose_name="Compra verificada"
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Visível"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviews",
                        to="api.orderitem",
                        verbose_name="Item do pedido",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="api.product",
                        verbose_name="Peça",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "db_table": "product_reviews",
                "ordering": ["-created_at"],
                "unique_together": {("product", "user", "order_item")},
            },
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Expira em")),
                (
                    "released",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Liberada"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="api.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to="api.product",
                        verbose_name="Peça",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_reservations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva de estoque",
                "verbose_name_plural": "Reservas de estoque",
                "db_table": "stock_reservations",
                "indexes": [
                    models.Index(
                        fields=["product", "released", "expires_at"],
                        name="stock_reser_product_d6cc6a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductVehicleCompatibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_compatibilities",
                        to="api.product",
                        verbose_name="Peça",
                    ),
                ),
                (
                    "vehicle_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="api.vehiclemodel",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compatibilidade veicular",
                "verbose_name_plural": "Compatibilidades veiculares",
                "db_table": "product_vehicle_compatibilities",
                "unique_together": {("product", "vehicle_model")},
            },
        ),
    ]
