# Generated by Django 5.2.12 on 2026-06-19 16:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_marketplace_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fulfillment_seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfillment_orders",
                to="api.seller",
                verbose_name="Loja responsável pelo envio",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="part_condition",
            field=models.CharField(
                choices=[
                    ("new", "Nova"),
                    ("used", "Usada"),
                    ("reconditioned", "Recondicionada"),
                ],
                default="new",
                max_length=20,
                verbose_name="Condição",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="part_origin",
            field=models.CharField(
                choices=[
                    ("original", "Original (OEM)"),
                    ("parallel", "Paralela"),
                    ("remanufactured", "Remanufaturada"),
                ],
                default="original",
                max_length=20,
                verbose_name="Origem",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Visualizações"),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_days",
            field=models.PositiveIntegerField(
                default=90, verbose_name="Garantia (dias)"
            ),
        ),
        migrations.CreateModel(
            name="InvoiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnpj", models.CharField(max_length=20, verbose_name="CNPJ")),
                (
                    "company_name",
                    models.CharField(max_length=255, verbose_name="Razão social"),
                ),
                (
                    "company_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        verbose_name="E-mail fiscal",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Solicitada"),
                            ("processing", "Em emissão"),
                            ("issued", "Emitida"),
                            ("rejected", "Rejeitada"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=80,
                        verbose_name="Número NF-e",
                    ),
                ),
                (
                    "invoice_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="PDF/XML"
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_requests",
                        to="api.order",
                        verbose_name="Pedido",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_requests",
                        to="api.seller",
                        verbose_name="Vendedor",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "db_table": "invoice_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "payment_preference_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "db_table": "order_groups",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="order_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="api.ordergroup",
                verbose_name="Grupo de checkout",
            ),
        ),
        migrations.CreateModel(
            name="UserNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("order_paid", "Pagamento confirmado"),
                            ("order_shipped", "Pedido enviado"),
                            ("order_tracking", "Rastreio atualizado"),
                            ("seller_new_order", "Nova venda"),
                            ("chat_message", "Nova mensagem"),
                            ("return_opened", "Devolução aberta"),
                            ("return_approved", "Devolução aprovada"),
                            ("payout_paid", "Saque pago"),
                            ("invoice_issued", "Nota fiscal emitida"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("link", models.CharField(blank=True, default="", max_length=500)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "db_table": "user_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductViewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="api.product",
                        verbose_name="Peça",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_views",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_view_events",
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="product_vie_product_5ea47d_idx",
                    )
                ],
            },
        ),
    ]
